# coding: utf-8

"""
    SerpsBot

    Our APIs allow data miners to harvest huge volumes of data from Google and other search engines.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import serpsbot
from serpsbot.models.featured_snippet import FeaturedSnippet  # noqa: E501
from serpsbot.rest import ApiException


class TestFeaturedSnippet(unittest.TestCase):
    """FeaturedSnippet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFeaturedSnippet(self):
        """Test FeaturedSnippet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = serpsbot.models.featured_snippet.FeaturedSnippet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
