# coding: utf-8

"""
    SerpsBot

    Our APIs allow data miners to harvest huge volumes of data from Google and other search engines.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import serpsbot
from serpsbot.models.app_apis_google_organic_schemas_search_request import AppApisGoogleOrganicSchemasSearchRequest  # noqa: E501
from serpsbot.rest import ApiException


class TestAppApisGoogleOrganicSchemasSearchRequest(unittest.TestCase):
    """AppApisGoogleOrganicSchemasSearchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppApisGoogleOrganicSchemasSearchRequest(self):
        """Test AppApisGoogleOrganicSchemasSearchRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = serpsbot.models.app_apis_google_organic_schemas_search_request.AppApisGoogleOrganicSchemasSearchRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
