# coding: utf-8

"""
    SerpsBot

    Our APIs allow data miners to harvest huge volumes of data from Google and other search engines.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import serpsbot
from serpsbot.api.google_news_api_api import GoogleNewsAPIApi  # noqa: E501
from serpsbot.rest import ApiException


class TestGoogleNewsAPIApi(unittest.TestCase):
    """GoogleNewsAPIApi unit test stubs"""

    def setUp(self):
        self.api = GoogleNewsAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_news_results_google_news_post(self):
        """Test case for get_news_results_google_news_post

        Get News Results  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
