# coding: utf-8

"""
    SerpsBot

    Our APIs allow data miners to harvest huge volumes of data from Google and other search engines.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import serpsbot
from serpsbot.models.extended_search_request import ExtendedSearchRequest  # noqa: E501
from serpsbot.rest import ApiException


class TestExtendedSearchRequest(unittest.TestCase):
    """ExtendedSearchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExtendedSearchRequest(self):
        """Test ExtendedSearchRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = serpsbot.models.extended_search_request.ExtendedSearchRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
