# coding: utf-8

"""
    SerpsBot

    Our APIs allow data miners to harvest huge volumes of data from Google and other search engines.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import serpsbot
from serpsbot.models.jobs_field import JobsField  # noqa: E501
from serpsbot.rest import ApiException


class TestJobsField(unittest.TestCase):
    """JobsField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobsField(self):
        """Test JobsField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = serpsbot.models.jobs_field.JobsField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
