# coding: utf-8

"""
    SerpsBot

    Our APIs allow data miners to harvest huge volumes of data from Google and other search engines.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import serpsbot
from serpsbot.api.google_videos_api_api import GoogleVideosAPIApi  # noqa: E501
from serpsbot.rest import ApiException


class TestGoogleVideosAPIApi(unittest.TestCase):
    """GoogleVideosAPIApi unit test stubs"""

    def setUp(self):
        self.api = GoogleVideosAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_videos_google_videos_post(self):
        """Test case for get_videos_google_videos_post

        Get Videos  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
