# coding: utf-8

"""
    SerpsBot

    Our APIs allow data miners to harvest huge volumes of data from Google and other search engines.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SuggestionRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'gl': 'str',
        'hl': 'str',
        'keywords': 'list[str]'
    }

    attribute_map = {
        'gl': 'gl',
        'hl': 'hl',
        'keywords': 'keywords'
    }

    def __init__(self, gl='US', hl='en_US', keywords=None):  # noqa: E501
        """SuggestionRequest - a model defined in Swagger"""  # noqa: E501
        self._gl = None
        self._hl = None
        self._keywords = None
        self.discriminator = None
        if gl is not None:
            self.gl = gl
        if hl is not None:
            self.hl = hl
        self.keywords = keywords

    @property
    def gl(self):
        """Gets the gl of this SuggestionRequest.  # noqa: E501

        The ISO code of the country for which you want to get the suggestions for.  # noqa: E501

        :return: The gl of this SuggestionRequest.  # noqa: E501
        :rtype: str
        """
        return self._gl

    @gl.setter
    def gl(self, gl):
        """Sets the gl of this SuggestionRequest.

        The ISO code of the country for which you want to get the suggestions for.  # noqa: E501

        :param gl: The gl of this SuggestionRequest.  # noqa: E501
        :type: str
        """

        self._gl = gl

    @property
    def hl(self):
        """Gets the hl of this SuggestionRequest.  # noqa: E501

        The language to get the suggestions for.  # noqa: E501

        :return: The hl of this SuggestionRequest.  # noqa: E501
        :rtype: str
        """
        return self._hl

    @hl.setter
    def hl(self, hl):
        """Sets the hl of this SuggestionRequest.

        The language to get the suggestions for.  # noqa: E501

        :param hl: The hl of this SuggestionRequest.  # noqa: E501
        :type: str
        """

        self._hl = hl

    @property
    def keywords(self):
        """Gets the keywords of this SuggestionRequest.  # noqa: E501

        The list of keywords to get suggestions for.  # noqa: E501

        :return: The keywords of this SuggestionRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._keywords

    @keywords.setter
    def keywords(self, keywords):
        """Sets the keywords of this SuggestionRequest.

        The list of keywords to get suggestions for.  # noqa: E501

        :param keywords: The keywords of this SuggestionRequest.  # noqa: E501
        :type: list[str]
        """
        if keywords is None:
            raise ValueError("Invalid value for `keywords`, must not be `None`")  # noqa: E501

        self._keywords = keywords

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SuggestionRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SuggestionRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
